version: "3.7"
services:
  front:
    image: rottiakash/resnal-frontend
    container_name: resnal-frontend
    networks:
      - resnal
  back:
    image: rottiakash/resnal-backend
    volumes: 
      - ./Backend:/app
  loadbal:
    image: rottiakash/resnal-loadbal
    networks: 
      - resnal
    volumes: 
      - ./Backend/resnal.sock:/app/resnal.sock
    ports: 
      - 80:80
    depends_on: 
      - "back"
networks: 
  resnal: