# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0002_fetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
