# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0003_auto_20180910_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetch',
            old_name='initial',
            new_name='res',
        ),
        migrations.AddField(
            model_name='fetch',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='section',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='sem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('usn', 'sem')]),
        ),
    ]
