# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0004_auto_20180911_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
