# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0007_auto_20180911_1903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fetch',
            unique_together=set([('res', 'subcode', 'subname')]),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('usn', 'sem', 'batch')]),
        ),
    ]
