# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0008_auto_20181003_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetch',
            old_name='res',
            new_name='usn',
        ),
        migrations.AlterUniqueTogether(
            name='fetch',
            unique_together=set([('usn', 'subcode', 'subname')]),
        ),
    ]
