# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0010_auto_20181007_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='subcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
