# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0011_analysis_subcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis',
            new_name='Analize',
        ),
    ]
