# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0012_auto_20181007_0714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analize',
            unique_together=set([('batch', 'sem', 'sec', 'subcode')]),
        ),
    ]
