# Generated by Django 2.2.1 on 2019-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0014_auto_20190314_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetch',
            name='FCD',
            field=models.CharField(default='DEF', max_length=3),
            preserve_default=False,
        ),
    ]
