# Generated by Django 2.2.3 on 2019-08-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0016_result_totalfcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetch',
            name='FCD',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='totalFCD',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
