# Generated by Django 2.2.3 on 2019-10-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0018_auto_20190817_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('usn', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=1, null=True)),
                ('batch', models.IntegerField(null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='analize',
            name='subcode',
            field=models.CharField(max_length=8),
        ),
    ]
