# Generated by Django 2.2.3 on 2020-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resanal', '0019_auto_20191029_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('batch', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('sem', models.IntegerField()),
                ('done', models.BooleanField()),
            ],
            options={
                'db_table': 'Data',
            },
        ),
    ]
